apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: capc-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: capc-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: capc-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - "--leader-elect"
        - "--v=${CAPC_LOGLEVEL:=0}"
        - "--diagnostics-address=${CAPC_DIAGNOSTICS_ADDRESS:=:8443}"
        - "--insecure-diagnostics=${CAPC_INSECURE_DIAGNOSTICS:=false}"
        - "--cloudstackcluster-concurrency=${CAPC_CLOUDSTACKCLUSTER_CONCURRENCY:=10}"
        - "--cloudstackmachine-concurrency=${CAPC_CLOUDSTACKMACHINE_CONCURRENCY:=10}"
        - "--cloudstackaffinitygroup-concurrency=${CAPC_CLOUDSTACKAFFINITYGROUP_CONCURRENCY:=5}"
        - "--cloudstackfailuredomain-concurrency=${CAPC_CLOUDSTACKFAILUREDOMAIN_CONCURRENCY:=5}"
        image: controller:latest
        name: manager
        ports:
          - containerPort: 9440
            name: healthz
            protocol: TCP
          - containerPort: 8443
            name: metrics
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9440
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsUser: 65532
          runAsGroup: 65532
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
