---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.cloudstackcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackclustertemplate
  failurePolicy: Fail
  name: mcloudstackclustertemplate.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackclustertemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cloudstackcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cloudstackmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cloudstackmachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackmachinetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta3-cloudstackclustertemplate
  failurePolicy: Fail
  name: vcloudstackclustertemplate.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackclustertemplates
  sideEffects: None
