---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackaffinitygroups
  - cloudstackclusters
  - cloudstackfailuredomains
  - cloudstackisolatednetworks
  - cloudstackmachines
  - cloudstackmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackaffinitygroups/finalizers
  - cloudstackclusters/finalizers
  - cloudstackfailuredomains/finalizers
  - cloudstackisolatednetworks/finalizers
  - cloudstackmachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackaffinitygroups/status
  - cloudstackisolatednetworks/status
  - cloudstackmachines/status
  - cloudstackmachinetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackclusters/status
  - cloudstackfailuredomains/status
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackmachinetemplate
  verbs:
  - get
  - list
  - watch
