apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
kind: CloudStackFailureDomain
metadata:
  name: failure-domain-1
spec:
  name: failure-domain-1
  zone:
    name: zone1
    network:
      name: guest-network-1
  acsEndpoint:
    name: cloudstack-credentials
    namespace: default
