name: Test coverage
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - name: Calculate go version
        id: vars
        run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: Run go test with coverage
        run: COVER_PROFILE=coverage.txt make test
      - name: Codecov upload
        uses: codecov/codecov-action@v7.0.0
        with:
          files: ./cover.out
