name: PR Check

on:
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.2
          args: --timeout=5m

  build:
    name: Test & Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run unit tests
        run: make test

      - name: Build
        run: make build